spring.config.import=optional:file:.env[.properties]
spring.application.name=GarageBook

#Security 
security.jwt.secret-key=${SECRET_KEY}
security.jwt.expiration-time=2592000000
 
#mysql
# Database Connection Details
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MySQL Platform (for Hibernate to generate correct SQL dialect)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#session
spring.session.jdbc.initialize-schema=always

#server
server.port=8080

#Meta
whatsapp.access-token=${WHATSAPP_API_ACCESS_TOKEN}
whatsapp.phone-number-id=${WHATSAPP_API_PHONE_NUMBER_ID}
whatsapp.graph-api-version=${WHATSAPP_API_GRAPH_API_VERSION}

#Frontend
frontend.url=${FRONTEND_URL}

# Spring AI OpenAI Configuration (Redirected to Cerebras)
spring.ai.openai.api-key=${CEREBRAS_API_KEY}
spring.ai.openai.base-url=https://api.cerebras.ai/v1
spring.ai.openai.chat.options.model=llama3.1-8b